### ISSUE TITLE
How to use SourceWithOffsetContext with a RestartSource

### ISSUE THREAD

**Issue by ayoung** [akkadotnet/Akka.Streams.Kafka#132]
Trying to use `KafkaConsumer.SourceWithOffsetContext` with a `RestartSource.WithBackoff()` but it does not seem possible. `KafkaConsumer.SourceWithOffsetContext()` returns a `SourceWithContext<ICommittableOffset, ConsumeResult<K, V>, IControl>` which is not compatible with what `WithBackoff()` expects. Basically `SourceWithContext<,>` cannot be cast to `Source<,>`.

As a work around, I'm using the [Polly lib](https://github.com/App-vNext/Polly) to introduce retries.

**Comment by hyperlobic** [comment]
Did you try using .AsSource() to convert back to Source<,>?

https://getakka.net/api/Akka.Streams.Dsl.SourceWithContext-3.html#methods
