### ISSUE TITLE
How can we get notified when a Kafka Consumer is rebalanced?

### ISSUE THREAD

**Issue by ayoung** [akkadotnet/Akka.Streams.Kafka#141]
The title says it all.

**Comment by IgorFedchenko** [comment]
Hmm... `SingleSourceStageLogic` as well as some other stage base classes have virtual `AddToPartitionAssignmentHandler` method which allows to customize handling of rebalance events.
So in theory, someone could override this logic with own implementation to override this method, and then override required stage (i.e. `PlainSourceStage`) to use this new logic implementation, and create another method like `KafkaConsumer.MyPlainSource` to be able to pass additional handling parameters...

But that would require `SingleSourceStageLogic` to be public, since it is internal now.

@ayoung Does this make sense for you? I mean, probably we could make that class public so that everyone could extent it like I described above to be able to handle rebalance events. If this is clear enough to go. 
But I doubt that there is another handy way to allow what you need.

**Comment by ayoung** [comment]
I'm not real familiar with the internals of this library so: does it make sense to me? No. 😉 But yes, some extensibility points would be helpful here. We are using this library to stream events from IoT devices and we create shadow actors to keep track of the state of these devices as events are streamed in from the source. If the consumers get rebalanced, we would like to about this so that we can remove all the shadow actors and start empty.

**Comment by ayoung** [comment]
I'm looking at the source a little closer. Even if we inherit from `SingleSourceStageLogic`, how do we change the stage classes (i.e. `SourceWithOffsetContextStage`) to use the super class? [These classes are hard coded](https://github.com/akkadotnet/Akka.Streams.Kafka/blob/4ea68b45d1c12bf8174cb71aaf7f2ec802d2e70d/src/Akka.Streams.Kafka/Stages/Consumers/Concrete/SourceWithOffsetContextStage.cs#L54) to use `SingleSourceStageLogic`.

**Comment by IgorFedchenko** [comment]
I think we will need to make `SourceWithOffsetContextStage` and other stages public classes, so that you could inherit from it and override `AddToPartitionAssignmentHandler` there.

**Comment by ayoung** [comment]
@IgorFedchenko I tried what you suggested. Made the `SourceWithOffsetContextStage` public along with their friends. It also required me to make `CommittableSourceStage` public. While, I do think that this would work, it makes the API for extending functionality just not that great. First I would have to inherit from `SourceWithOffsetContextStage`, then also inherit from `CommittableSourceStage` to override the `Logic()` function. Not only that but I would have to know about how to instantiate my `CustomSourceWithOffsetContextStage` and know the consequences of not implementing the `GetMessageBuilder()` correctly. Of course, I could just copy/paste the code to my superclass but MEH! People doing this would need to know too much of the internals to extend the functionality which is why I think you made these classes `internal` in the first place.

My opinion here is that `SingleSourceStageLogic` should provide an option to wait for the stream to drain when partitions get revoked and optionally accept some kind of callback/notification when this happens. It is quite a common thing in Kafka consuming applications to need to purge state when consumers get rebalanced -- I'm surprised that this functionality isn't just built in.

If you agree, I can try to go that direction.

**Comment by ayoung** [comment]
Any feedback on this?

**Comment by Aaronontheweb** [comment]
@IgorFedchenko should be getting back to you soon @ayoung

**Comment by IgorFedchenko** [comment]
@ayoung Sorry for a big delay here.
So you are right, and this feature is something that should be built it - and that's what original Alpakka Kafka project have added [in version 2.0.0](https://doc.akka.io/docs/alpakka-kafka/current/consumer-rebalance.html#partition-assignment-handler) after this port was actually finished.

I have added separate issue for this: https://github.com/akkadotnet/Akka.Streams.Kafka/issues/149 Once it is resolved, you should be able to handle assign/revoke events with your `IPartitionEventHandler` implementation (this interface is `internal` now, so going to make it public).

**Comment by IgorFedchenko** [comment]
So I am going to add support for this in next few days.

**Comment by ayoung** [comment]
Thank you. Looking forward to this.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko I don't believe we have nightly build support for Akka.Streams.Kafka but it should be easy to add it

**Comment by ayoung** [comment]
Thank you @IgorFedchenko. See comment/question in the PR.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko @ayoung is this resolved? added it to the current sprint beginning tomorrow.

**Comment by IgorFedchenko** [comment]
I think we have very detailed discussion in assigned PR (https://github.com/akkadotnet/Akka.Streams.Kafka/pull/154), and this issue is resolved - there is a way to get notified when consumer is rebalanced.
