### ISSUE TITLE
How to apply further settings to the underlying kafka producer and consumer?

### ISSUE THREAD

**Issue by realvictorprm** [akkadotnet/Akka.Streams.Kafka#165]
I'm currently trying to get the max performance and best reliability out of my Akka Streams application targeting Kafka. To do so I would like to apply further settings which are mentioned in this issue [here](https://github.com/confluentinc/confluent-kafka-dotnet/issues/696#). Any idea how this can be done?

**Comment by IgorFedchenko** [comment]
Yeah, there are lots of parameters that can be configured for consumer / producer from confluent kafka library. 

The only way to do that right now is to set them programmatically, using `WithProperty` method when building settings. Here is an example of how we do that in our test suite: https://github.com/akkadotnet/Akka.Streams.Kafka/blob/3dd904e6d62d49de0ab334fff5152a6162d37fba/src/Akka.Streams.Kafka.Tests/KafkaIntegrationTests.cs#L68

**Comment by IgorFedchenko** [comment]
@realvictorprm Feel free to reopen or ask additional questions here 👍
