### ISSUE TITLE
Publish to NuGet

### ISSUE THREAD

**Issue by pzartem** [akkadotnet/Akka.Streams.Kafka#18]
Is it possible to publish this to NuGet like this one https://www.nuget.org/packages/Akka.Streams.Amqp/?

**Comment by marcpiechura** [comment]
Cc @Aaronontheweb @alexvaluyskiy

**Comment by Aaronontheweb** [comment]
Done, taken care of in https://github.com/akkadotnet/Akka.Streams.Kafka/releases/tag/0.5.0
