### ISSUE TITLE
Add support for custom statistics handler

### ISSUE THREAD

**Issue by hannesstockner** [akkadotnet/Akka.Streams.Kafka#201]
Hi,

the `Confluent.Kafka.ConsumerBuilder` provides a function to set a custom statistics handler `SetStatisticsHandler(Action<IConsumer<TKey, TValue>, String>`.

It would be great if we could pass a custom handler to the Subscription, similar as we can do that with the `IPartitionEventHandler`.

Thanks.

**Comment by IgorFedchenko** [comment]
@hannesstockner That makes sense. While we are trying to keep as close as possible to scala implementation, defenitely need to support Confluent driver features like that.

Basically, we will need to add something like `IStatisticsHandler` interface with `void Handle(IConsumer consumer, string>()` method, add optional parameter to `Subscription` classes like we do with `IPartitionEventHandler`, and then use it during actual consumer creation.

Do you think you could give it a try and create some PR for that? Or need help of mine/other core team members?

**Comment by hannesstockner** [comment]
Thanks a lot for your response @IgorFedchenko . @jsb81 and myself started to have a detailed look at the code and we will create a PR tomorrow.

**Comment by IgorFedchenko** [comment]
Closed by #204

**Comment by IgorFedchenko** [comment]
We are making a `1.1.3` release shortly, you will get this update there guys.
