### ISSUE TITLE
[CRITICAL] Need to stop polling for new messages when there is no downstream demand

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Streams.Kafka#245]
Going to keep this issue simple because it's not clear from looking at the `KafkaConsumerActor` code, but I think we keep polling even when there is no demand downstream.

The polling _has to stop_ when there is no downstream demand. Consumer offsets must _never be advanced_ by our producer stages until after those messages are pumped downstream, otherwise data loss issues such as https://github.com/akkadotnet/Akka.Streams.Kafka/issues/232 will occur in the event of an error.

What happens right now when downstream backpressures @IgorFedchenko @Arkatufus ? Does the polling just keep going?

**Comment by Arkatufus** [comment]
C# side:
Consume() => SafeKafkaHandle.ConsumerPoll() => Librdkafka.consumer_poll() => (interop)rd_kafka_consumer_poll

C++ side:
rd_kafka_consumer_poll() => rd_kafka_consume0()

rd_kafka_consume0 does a loop that calls rd_kafka_q_pop which calls rd_kafka_q_pop_serve which calls rd_kafka_op_handle
rd_kafka_op_handle inspects each messages from the queue, and if it has a callback, it will call it. It will return HANDLED if the callback handled the message, or PASS if its not handled. If it is a PASS, it is then bubbled back to the caller, inspected to see if it needs to be handled, and if not then returned to the caller of Consume()

So if we stop calling Consume, none of these messages will ever be processed by the internal callbacks.

I'm not sure if any of these messages are important, if there is a separate queue of incoming and outgoing messages, and if we stop doing polls, it'll break transaction/commits or not.

**Comment by Aaronontheweb** [comment]
I think the timing of the callbacks being performed is less important - so long as we're not advancing the `Offset`s without passing messages downstream it shouldn't matter. 

Having less data "in flight" past the end of the Kafka consumer is generally safer as it stops us from getting out "ahead" of where the consumer is relative to the broker. Having stale data sitting inside the buffer that belongs to a partition we no longer own, for instance, is a major concern - once that data leaves the Consumer Stage we lose control over it. 

> if we stop doing polls, it'll break transaction/commits or not.

Having the consumer continuously running on auto-pilot is what breaks this and that's what the current capabilities look like now.

**Comment by Aaronontheweb** [comment]
Relevant issue from a year ago on the original JVM implementation: https://github.com/akka/alpakka-kafka/pull/1263

I think our issues run deeper than that, but that issue does a great job explaining why Akka.Streams "stale state" is such a hazard. Keep as much data as possible _in Kafka_ so these rebalancing / other broker-consumer issues don't have side effects inside end-user applications.

**Comment by Aaronontheweb** [comment]
I think this issue was based on a misunderstanding of how the C# Kafka client works internally. After a thorough review with @Arkatufus I'm convinced this is no longer an issue.
