### ISSUE TITLE
Need to add "reasonable" default `Decider` to filter out hard failures from soft ones

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/Akka.Streams.Kafka#252]
The default decider implementation should throw when this gets raised currently - but shouldn't we just ignore this error by default? Because there's instances where a user can request partitions / topics that haven't been created yet.

_Originally posted by @Aaronontheweb in https://github.com/akkadotnet/Akka.Streams.Kafka/pull/246#discussion_r749425902_

**Comment by Aaronontheweb** [comment]
We should not blow up Akka.Streams.Kafka graphs when "normal" errors occur:

1. Idle connections being reaped by broker;
2. Requesting topics / partitions that haven't been created yet;
3. What else from this list? https://github.com/akkadotnet/Akka.Streams.Kafka/issues/184#issuecomment-963468130

**Comment by Aaronontheweb** [comment]
> Serialization errors (requires some special handling - end users are going to need to decide what to do; skip message or crash. Need documentation on how to do both.)

This needs to be documented before we can release 1.2.0. Need to explain how to commit past a poisoned message on the consumer or how to let the stream blow up and be restarted via supervision.

**Comment by Aaronontheweb** [comment]
@Arkatufus would a better way of doing this be: when _should_ we blow up vs. when shouldn't we? Looks like most of these errors are informational at best.

**Comment by Arkatufus** [comment]
@Aaronontheweb looks like the exception list in the Java API reference is a better source for research, they actually explain what the error code ment and what caused them

**Comment by Aaronontheweb** [comment]
@Arkatufus let's reference it in this issue then.
