### ISSUE TITLE
Provide defaults for consumer supervision strategy on Restart

### ISSUE THREAD

**Issue by IgorFedchenko** [akkadotnet/Akka.Streams.Kafka#33]
Right now we have error handling like this:
https://github.com/IgorFedchenko/Akka.Streams.Kafka/blob/02d0f046a76482a444481a681175917f526c5b89/src/Akka.Streams.Kafka/Stages/CommittableConsumerStage.cs#L165-L183

So, when decision is to restart stage, we need to something else then just resume.

@Aaronontheweb I guess we need to dispose current consumer and create another one here. 
I am still little bit new with Akka.Streams - so is there some handy way to stop stage and start again without delivering failure to the user? This will do exactly what we need - will do consumer.Dispose() in PostStop call and then recreate it.

**Comment by Aaronontheweb** [comment]
There are some built-in stages that can do this - how does the original Alpakka-Kafka project do this?

**Comment by IgorFedchenko** [comment]
Got your point, will check this out when return to this issue.
