### ISSUE TITLE
Support for Akka.net v1.3.16

### ISSUE THREAD

**Issue by seungyongshim** [akkadotnet/Akka.Streams.Kafka#94]
Excuse, me.

Akka.net v1.3.16

Would you have a any other plan for Akka.net v1.3.16? v1.3.16 is main stream, isn't it?
Dev team dislikes beta on the beta.

Regards

**Comment by Aaronontheweb** [comment]
We're going to release Akka.NET v1.4.0 soon - can't really backport this to support an older version of Akka.NET because it depends on v1.4.0 features.
